### ISSUE TITLE
Outdated embedded redis dependency causes test failures as redis does not start

### ISSUE THREAD

**Issue by nashjain** [camaraproject/QualityOnDemand_PI1#17]
**Problem description**
Both RedisQosProfileServiceTest and SessionsControllerIntegrationTest fails as embedded redis does not startup

**Expected action**

1. Run mvn clean test
2. In the logs you will see
[ERROR] Errors:
[ERROR]   SessionsControllerIntegrationTest.setUp:158 » Runtime Can't start redis server. Check logs for details. Redis process log:
[ERROR]   RedisQosProfileServiceTest.setUp:61 » Runtime Can't start redis server. Check logs for details. Redis process log:
[INFO]
[ERROR] Tests run: 74, Failures: 0, Errors: 2, Skipped: 0
3. Caused by [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.119 s <<< FAILURE! -- in com.camara.qod.service.RedisQosProfileServiceTest
[ERROR] com.camara.qod.service.RedisQosProfileServiceTest -- Time elapsed: 0.119 s <<< ERROR!
java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log:
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:70)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:42)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
	at com.camara.qod.service.RedisQosProfileServiceTest.setUp(RedisQosProfileServiceTest.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

**Additional context**
This is happening on MacOS 14.5 and openjdk 17.0.2 2022-01-18

**Comment by dfischer-tech** [comment]
Hi @nashjain, 
As a minor workaround, simply replacing the line:
`redisServer = new RedisServer(6370);`
with:
`RedisServer.builder().port(6370).setting("maxheap 128M").build();`
would have sufficed.

However, I am generally in favour of updating outdated embedded test Redis dependencies. 
Therefore, I am satisfied with your pull request.

Best regards,
Domi

**Comment by nashjain** [comment]
Hi @maxl2287,

Even after updating the code to use RedisServer.builder().port(6370).setting("maxheap 128M").build();

I'm still getting this error:

java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log: 

	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:70)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:42)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
	at com.camara.qod.service.RedisQosProfileServiceTest.setUp(RedisQosProfileServiceTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)


Process finished with exit code 255
